import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

// Optional browser check: supply an installed Playwright module and Chromium executable.
const require = createRequire(import.meta.url);
const { chromium } = require(process.argv[2] || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.argv[3] ? { executablePath: process.argv[3] } : {}) });
const errors = [];
const context = await browser.newContext({ viewport: { width:1440, height:1000 }, acceptDownloads:true, reducedMotion:'reduce' });
const page = await context.newPage();
page.on('pageerror', e => errors.push(e.message));
page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
const click = action => page.locator(`#app [data-action="${action}"]`).first().click();
await mkdir('reference/verification', { recursive:true });
try {
  await page.goto('http://localhost:5173/payments');
  await page.screenshot({path:'reference/verification/01-desktop.png',fullPage:true});
  await page.locator('[data-type="abroad"]').click();
  await page.screenshot({path:'reference/verification/02-countries.png'});
  await page.getByLabel('Поиск страны').fill('Неизвестная');
  assert.match(await page.locator('#country-list').innerText(),/не найдена/);
  await page.getByLabel('Поиск страны').fill('тадж');
  await page.locator('[data-country="Таджикистан"]').click();
  assert.match(await page.locator('.methods-title').innerText(),/Таджикистан/);
  await click('phone-method');
  await page.getByLabel('Ваше сообщение').fill('На текущие расходы');
  await click('recipient');
  await page.getByLabel('Номер телефона получателя',{exact:true}).fill('123');
  await click('find-banks');
  assert.match(await page.locator('#phone-error').innerText(),/Проверьте номер/);
  await click('sample-phone');
  await click('find-banks');
  await page.screenshot({path:'reference/verification/05-banks.png'});
  await click('select-bank');
  await page.locator('[data-purpose="1"]').click();
  await page.keyboard.type('99');
  await click('review');
  assert.match(await page.locator('#amount-error').innerText(),/Минимальная/);
  await page.locator('[data-amount="500"]').click();
  assert.equal(await page.locator('#amount-display').innerText(),'500');
  await page.screenshot({path:'reference/verification/07-amount.png'});
  await click('review');
  assert.match(await page.locator('.confirmation-content').innerText(),/51,65 TJS/);
  assert.match(await page.locator('.confirmation-content').innerText(),/На текущие расходы/);
  await page.screenshot({path:'reference/verification/08-confirmation.png'});
  await click('send');
  await page.locator('#app').getByRole('heading',{name:'Перевод выполнен'}).waitFor();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('alfa-transfer-prototype-v1')).length),1);
  const [download] = await Promise.all([page.waitForEvent('download'),click('receipt')]);
  assert.match(download.suggestedFilename(),/^demo-transfer-.*\.txt$/);
  await download.saveAs('reference/verification/demo-receipt.txt');
  await page.screenshot({path:'reference/verification/09-success.png'});
  await page.locator('#app .bottom-nav [data-page="history"]').click();
  assert.equal(await page.locator('.history-item').count(),1);
  await page.reload();
  await page.locator('#app .bottom-nav [data-page="home"]').click();
  assert.match(await page.locator('.balance-card').innerText(),/3\s000,35/);
  await page.locator('#app .bottom-nav [data-page="history"]').click();
  assert.equal(await page.locator('.history-item').count(),1);
  await page.locator('.history-item').click();
  await page.locator('#app').getByRole('heading',{name:'Перевод выполнен'}).waitFor();
  console.log('PASS: Eight-step scenario, invalid phone and amount, quote, send, receipt, balance, persistent history.');

  await page.locator('#reset').click();
  for (const country of ['Беларусь','Кыргызстан','Таджикистан','Узбекистан']) {
    await page.locator('[data-type="abroad"]').click();
    await page.getByLabel('Поиск страны').fill(country);
    await page.locator(`[data-country="${country}"]`).click();
    await click('phone-method');
    await click('recipient');
    if (await page.locator('[data-action="sample-phone"]').count()) { await click('sample-phone'); await click('find-banks'); }
    await click('select-bank');
    await page.locator('[data-purpose="1"]').click();
    await page.locator('[data-amount="500"]').click();
    await click('review');
    assert.match(await page.locator('.confirmation-content').innerText(),new RegExp(country));
    await page.locator('#reset').click();
  }
  console.log('PASS: All four country flows reach confirmation.');

  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'reference/verification/10-mobile-payments.png'});
  assert.equal(await page.locator('.guide').isVisible(),false);
  await page.locator('[data-type="abroad"]').click();
  await page.getByLabel('Поиск страны').fill('Таджикистан');
  await page.locator('[data-country="Таджикистан"]').click();
  await click('phone-method'); await click('recipient'); await click('sample-phone'); await click('find-banks'); await click('select-bank');
  await page.locator('[data-purpose="1"]').click();
  await page.locator('[data-amount="500"]').click();
  await page.screenshot({path:'reference/verification/11-mobile-amount.png'});
  await click('review');
  const detailBounds = await page.locator('.confirmation-content .detail').evaluateAll(items => items.map(item => {
    const label = item.querySelector('dt');
    const value = item.querySelector('dd');
    return {label:label.textContent,top:label.getBoundingClientRect().top,bottom:value.getBoundingClientRect().bottom};
  }));
  for (let i=1;i<detailBounds.length;i++) assert.ok(detailBounds[i].top >= detailBounds[i-1].bottom + 15, JSON.stringify(detailBounds));
  await page.screenshot({path:'reference/verification/12-mobile-confirmation.png'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true);
  await click('back');
  await page.setViewportSize({width:320,height:568});
  await page.screenshot({path:'reference/verification/13-small-mobile.png'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true);
  await click('review');
  assert.equal(await page.locator('[data-action="send"]').isVisible(),true);
  await click('send');
  await page.locator('#app').getByRole('heading',{name:'Перевод выполнен'}).waitFor();
  console.log('PASS: Mobile layout at 390×844 and 320×568; transfer can be completed.');
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#reference-toggle').click();
  assert.equal(await page.locator('#reference-dialog').isVisible(),true);
  assert.equal(await page.locator('#reference-image').evaluate(async img=>{ await img.decode(); return img.naturalWidth > 0; }),true);
  await page.locator('#reference-close').click();
  await page.locator('#app .bottom-nav [data-page="home"]').click();
  await click('reset-balance');
  await click('confirm-reset');
  assert.match(await page.locator('.balance-card').innerText(),/3\s500,35/);
  await page.locator('#app .bottom-nav [data-page="history"]').click();
  assert.equal(await page.locator('.history-item').count(),0);
  console.log('PASS: Reference comparison and demo balance reset.');
  assert.deepEqual(errors,[]);
  console.log('PASS: No browser exceptions or failed HTTP requests.');
} finally { await browser.close(); }
