import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = createRequire(import.meta.url)(process.argv[2] || 'playwright');
const browser = await chromium.launch({headless:true,...(process.argv[3]?{executablePath:process.argv[3]}:{})});
const base=process.argv[4]||'http://127.0.0.1:5173';
const page=await browser.newPage({viewport:{width:1440,height:1080},reducedMotion:'reduce'});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
const phone=page.frameLocator('#payments-frame');
const click=a=>phone.locator(`[data-action="${a}"]`).first().click();
const command=a=>page.locator(`[data-command="${a}"]`).click();
const status=part=>page.waitForFunction(p=>document.querySelector('#event-status').textContent.includes(p),part);
await mkdir('reference/verification',{recursive:true});
try {
  await page.goto(base);
  assert.equal(await page.locator('.bento-card').count(),5);
  await page.locator('.try-trigger').first().click();
  assert.equal(await page.locator('#try-dialog').isVisible(),true);
  for(const feature of ['behaviour','news','recommendation','prefill','scheduler']){
    await page.goto(`${base}/features/${feature}`);
    await phone.locator('.payments-screen').waitFor();
    assert.equal(await phone.locator('.transfer-tile').count(),5);
    await click('repeat-payment');
    assert.match(await phone.locator('#amount-display').innerText(),/16\s000/);
    await phone.locator('[data-amount="500"]').click();await click('review');
    assert.match(await phone.locator('.confirmation-content').innerText(),/51,65 TJS/);
    await page.locator('[data-mode="tech"]').click();
    assert.equal(await phone.locator('[data-action="send"]').count(),1);
    await page.locator('[data-table="transfers"], [data-table="global_notifications"]').first().click();
    assert.equal(await page.locator('#data-dialog').isVisible(),true);
    await page.locator('#data-close').click();
  }
  console.log('PASS: Five features share /payments forms, amount editing, confirmation and state across Product/Tech.');
  await page.goto(`${base}/features/behaviour`);await phone.locator('.payments-screen').waitFor();
  await page.locator('#income-toggle').uncheck();await command('push');await status('нет поступления');
  assert.equal(await phone.locator('.push-card').count(),0);
  await page.locator('#income-toggle').check();await page.locator('#window-toggle').uncheck();
  await command('push');await status('вне временного окна');
  await page.locator('#window-toggle').check();await command('push');await status('1 из 2');
  await phone.locator('.push-card').waitFor();
  assert.equal(await phone.locator('.push-wallpaper').getAttribute('src'),'/assets/push-home-screen.png');
  await phone.locator('.push-wallpaper').evaluate(img=>img.decode());
  assert.equal(await phone.locator('.push-wallpaper').evaluate(img=>img.naturalWidth),591);
  await page.screenshot({path:'reference/verification/feature-push-interactive.png',fullPage:true});
  await command('push');await status('Повтор исключён');
  await command('all-signals');await status('прогнозный');
  await command('push');await status('Лимит недели');
  await page.locator('[data-mode="tech"]').click();await page.locator('[data-table="completed_push"]').click();
  assert.equal(await page.locator('#data-table tbody tr').count(),2);
  assert.match(await page.locator('#data-table').innerText(),/behaviour/);
  assert.match(await page.locator('#data-table').innerText(),/history/);
  await page.locator('#data-close').click();
  await command('next-week');await status('новое поступление');
  await command('reset');await status('Восстановлены');
  await command('push');await status('1 из 2');await click('open-push');await click('review');await click('send');
  await phone.getByRole('heading',{name:'Перевод выполнен',exact:true}).waitFor();
  await command('push');await status('уже выполнен');
  console.log('PASS: Income/window gating, original background, dedup, priorities, cap and completed-transfer suppression.');
  await click('schedule-demo');
  await phone.locator('[name="amount"]').fill('17000');await phone.locator('[name="time"]').fill('15:30');
  await phone.locator('#schedule-form [type="submit"]').click();await click('confirm-schedule');
  await phone.locator('#schedule-confirm-no').click();await click('confirm-schedule');
  await phone.locator('#schedule-confirm-yes').click();await status('сохранена запись');
  await click('edit-schedule');
  await phone.locator('[name="amount"]').fill('12000');await phone.locator('[name="recipient"]').fill('Новый получатель');
  await phone.locator('[name="phone"]').fill('123');await phone.locator('#schedule-form [type="submit"]').click();
  assert.match(await phone.locator('#schedule-error').innerText(),/номер телефона/);
  await phone.locator('[name="phone"]').fill('+7 999 123-45-67');
  await phone.locator('[name="date"]').fill('2026-09-15');await phone.locator('[name="time"]').fill('09:45');
  await phone.locator('#schedule-form [type="submit"]').click();await click('confirm-schedule');
  await phone.locator('#schedule-confirm-yes').click();await status('сохранена запись');
  assert.match(await phone.locator('.screen-body').innerText(),/Новый получатель/);
  await page.reload();await phone.locator('.payments-screen').waitFor();await click('my-payments');
  assert.equal(await phone.locator('.schedule-item').count(),1);
  assert.match(await phone.locator('.schedule-item').innerText(),/12\s000/);
  await click('schedule-details');await click('cancel-schedule');await phone.locator('#schedule-confirm-yes').click();await status('отменил');
  assert.equal(await phone.locator('[data-action="edit-schedule"]').count(),0);
  await click('open-schedules');assert.match(await phone.locator('.schedule-item').innerText(),/Отменён/);
  console.log('PASS: Schedule review, confirmation, CRUD, validation and reload persistence.');
  for(const feature of ['news','recommendation']){
    await page.goto(`${base}/features/${feature}`);await phone.locator('.payments-screen').waitFor();
    await command('push');await phone.locator('.push-card').waitFor();await click('open-push');await click('review');await click('send');
    await phone.getByRole('heading',{name:'Перевод выполнен',exact:true}).waitFor();
  }
  await page.goto(`${base}/features/scheduler`);await phone.locator('.payments-screen').waitFor();
  await click('repeat-payment');await click('review');await click('send');
  await phone.getByRole('heading',{name:'Перевод выполнен',exact:true}).waitFor();await click('schedule-demo');
  await page.locator('[data-mode="tech"]').click();
  await page.screenshot({path:'reference/verification/feature-scheduler-interactive.png',fullPage:true});
  for(const width of [960,600,390,320]){
    await page.setViewportSize({width,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`outer overflow ${width}`);
    assert.equal(await phone.locator('html').evaluate(el=>el.scrollWidth<=innerWidth),true,`phone overflow ${width}`);
    if(width===390)await page.screenshot({path:'reference/verification/feature-scheduler-mobile.png',fullPage:true});
  }
  assert.deepEqual(errors,[]);
  console.log('PASS: News/prediction push-to-transfer journeys, responsive 960/600/390/320, no browser errors.');
} finally {await browser.close();}
